import { useEffect, useMemo, useState } from "react";
import Sidebar from "../../components/Sidebar";
import Navbar from "../../components/Navbar";
import api from "../../services/api";

function SkillAnalytics() {
  const [analytics, setAnalytics] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { api.get("/colleges/analytics").then(({ data }) => setAnalytics(data)).catch((err) => setError(err.response?.data?.message || "Unable to load skill analytics.")); }, []);
  const skills = analytics?.topSkills || [];
  const totalStudents = analytics?.totalStudents || 0;
  const strongest = skills[0];
  const gaps = useMemo(() => skills.map((item) => ({ ...item, coverage: totalStudents ? Math.round((item.count / totalStudents) * 100) : 0 })).sort((a, b) => a.coverage - b.coverage), [skills, totalStudents]);
  return <div className="dashboard-layout"><Sidebar type="college" /><main className="main-content"><Navbar title="Skill Analytics" subtitle="Understand student skill trends using real student profiles." />{error && <div className="error-message">{error}</div>}<div className="stats-grid">{[['Students Analyzed', totalStudents], ['Most Common Skill', strongest?.skill || 'No data'], ['Skill Coverage', strongest ? `${Math.round((strongest.count / Math.max(totalStudents, 1)) * 100)}%` : '0%'], ['Skills Tracked', skills.length]].map(([label, value]) => <div className="stat-card" key={label}><span className="stat-label">{label}</span><div className="stat-value">{value}</div><p className="stat-description">Based on current college data</p></div>)}</div><div className="card"><div className="section-title"><h2>Student Skill Distribution</h2><span>Current student profiles</span></div><div className="analytics-list">{skills.length ? skills.map((item) => { const pct = Math.round((item.count / Math.max(totalStudents, 1)) * 100); return <div className="analytics-item" key={item.skill}><div className="analytics-header"><div><strong>{item.skill}</strong><p>{item.count} students</p></div><strong>{pct}%</strong></div><div className="progress-bar"><div className="progress-fill" style={{ width: `${pct}%` }} /></div></div>; }) : <div className="no-results"><h3>No Skill Data</h3><p>Student skills will appear after profiles contain skill information.</p></div>}</div></div><div className="card"><div className="section-title"><h2>Skill Coverage</h2><span>Lowest coverage first</span></div><div className="training-list">{gaps.length ? gaps.map((item, index) => <div className="training-item" key={item.skill}><div className="training-number">{index + 1}</div><div><h3>{item.skill}</h3><p>{item.count} of {totalStudents} students · {item.coverage}% coverage</p></div></div>) : <div className="no-results"><h3>No Recommendations</h3><p>More student skill data is required.</p></div>}</div></div><div className="ai-info"><div className="ai-info-icon">✦</div><div><strong>Data-driven Skill Insight</strong><p>{gaps[0] ? `${gaps[0].skill} currently has the lowest coverage among the tracked student skills. Consider targeted training based on actual student profiles.` : 'Add student skills to generate a data-driven skill gap insight.'}</p></div></div></main></div>;
}
export default SkillAnalytics;
